services:
  flask-app:
    image: nivedhajd/flask-expense-tracker:latest
    image: nivedhajd/flask-expense-tracker:${IMAGE_TAG} 
    container_name: flask-expense-app
    ports:
      - "5000:5000"

    environment:
      FLASK_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    restart: always

    # Healthcheck (important for production)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3